### ISSUE TITLE
Вылетает периодически

### ISSUE THREAD

**Issue by s1nka** [QuiteRSS/quiterss#1192]
Либо сразу при запуске, либо рандомно вылетает.
OS: Debian x64.

```
Thread 15 "QNetworkAccessM" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff739ff700 (LWP 7302)]
0x00007ffff4289b84 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
(gdb) where
#0  0x00007ffff4289b84 in  () at /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#1  0x00007ffff4288c49 in  () at /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#2  0x00007ffff3f03d62 in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff78cb501 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff78d29b0 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff3eda029 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff3edd00b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff3f2bda3 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff20d59ee in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff20d5c88 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff20d5d1c in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff3f2b3c7 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff3ed8cfb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff3d28d8e in QThread::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff3d32a07 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff3bc0fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#16 0x00007ffff377c4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by Funcy-dcm** [comment]
Версия Qt какая?

**Comment by s1nka** [comment]
Qt версии 5.11.3.
Вопрос решился, когда с подписки удалил ленту с pikabu.ru. Больше вылетов не было.

**Comment by Funcy-dcm** [comment]
А можно ссылку на ленту, хочу у себя. И ещё опишите подробнее при каком действии происходил вылет

**Comment by s1nka** [comment]
[Ссылка на RSS](https://pikabu.ru/xmlfeeds.php?cmd=popular)
Вылетало в момент обновления ленты. Чаще при старте программы, когда все ленты обновляются. Реже в процессе работы.

**Comment by Funcy-dcm** [comment]
Проверил на версии 0.19.1 - всё нормально с этой лентой
