### ISSUE TITLE
QuiteRSS freezes on one feed due to gstreamer mutex

### ISSUE THREAD

**Issue by ValdikSS** [QuiteRSS/quiterss#1383]
Linux, Fedora 32, QuiteRSS 0.19.4 (21.04.2020).

QuiteRSS freezes when viewing "Gray Days and Gold, November 2020" post from https://markfgriffin.com/feed/ feed.
This feed contains Mixcloud audio player. When it's loaded and viewed, QuiteRSS freezes upon switching to another post (from either this feed or another).

Gdb backtrace shows that something is locked in gstreamer:

```
(gdb) bt
#0  0x00007ffff39bf37d in syscall () at /lib64/libc.so.6
#1  0x00007ffff21758ac in g_mutex_lock_slowpath () at /lib64/libglib-2.0.so.0
#2  0x00007fff7af5c4a7 in gst_adaptive_demux_change_state () at /lib64/libgstadaptivedemux-1.0.so.0
#3  0x00007fffc8062471 in gst_hls_demux_change_state () at /usr/lib64/gstreamer-1.0/libgsthls.so
#4  0x00007ffff247a5d2 in gst_element_change_state () at /lib64/libgstreamer-1.0.so.0
#5  0x00007ffff247ad1d in gst_element_set_state_func () at /lib64/libgstreamer-1.0.so.0
#6  0x00007ffff245669c in gst_bin_change_state_func () at /lib64/libgstreamer-1.0.so.0
#7  0x00007fffc80bfb92 in gst_decode_bin_change_state () at /usr/lib64/gstreamer-1.0/libgstplayback.so
#8  0x00007ffff247a5d2 in gst_element_change_state () at /lib64/libgstreamer-1.0.so.0
#9  0x00007ffff247ad1d in gst_element_set_state_func () at /lib64/libgstreamer-1.0.so.0
#10 0x00007ffff245669c in gst_bin_change_state_func () at /lib64/libgstreamer-1.0.so.0
#11 0x00007fffc80d52d9 in gst_uri_decode_bin_change_state () at /usr/lib64/gstreamer-1.0/libgstplayback.so
#12 0x00007ffff247a5d2 in gst_element_change_state () at /lib64/libgstreamer-1.0.so.0
#13 0x00007ffff247ad1d in gst_element_set_state_func () at /lib64/libgstreamer-1.0.so.0
#14 0x00007ffff245669c in gst_bin_change_state_func () at /lib64/libgstreamer-1.0.so.0
#15 0x00007fffc80f0414 in gst_play_bin_change_state () at /usr/lib64/gstreamer-1.0/libgstplayback.so
#16 0x00007ffff247a5d2 in gst_element_change_state () at /lib64/libgstreamer-1.0.so.0
#17 0x00007ffff247ad1d in gst_element_set_state_func () at /lib64/libgstreamer-1.0.so.0
#18 0x00007ffff623a169 in WebCore::MediaPlayerPrivateGStreamer::~MediaPlayerPrivateGStreamer() () at /lib64/libQt5WebKit.so.5
#19 0x00007ffff623a5ed in WebCore::MediaPlayerPrivateGStreamer::~MediaPlayerPrivateGStreamer() () at /lib64/libQt5WebKit.so.5
#20 0x00007ffff60efa52 in WebCore::MediaPlayer::~MediaPlayer() () at /lib64/libQt5WebKit.so.5
#21 0x00007ffff60efaed in WebCore::MediaPlayer::~MediaPlayer() () at /lib64/libQt5WebKit.so.5
#22 0x00007ffff5b85108 in WebCore::HTMLMediaElement::clearMediaPlayer(WebCore::HTMLMediaElementEnums::DelayedActionType) ()
    at /lib64/libQt5WebKit.so.5
#23 0x00007ffff5b851de in WebCore::HTMLMediaElement::userCancelledLoad() [clone .part.0] () at /lib64/libQt5WebKit.so.5
#24 0x00007ffff5b88f68 in WebCore::HTMLMediaElement::stopWithoutDestroyingMediaPlayer() () at /lib64/libQt5WebKit.so.5
#25 0x00007ffff5b89079 in non-virtual thunk to WebCore::HTMLMediaElement::stop() () at /lib64/libQt5WebKit.so.5
#26 0x00007ffff5c704a2 in WebCore::ScriptExecutionContext::stopActiveDOMObjects() [clone .part.0] () at /lib64/libQt5WebKit.so.5
#27 0x00007ffff5ccc608 in WebCore::Document::prepareForDestruction() () at /lib64/libQt5WebKit.so.5
#28 0x00007ffff6024004 in WebCore::Frame::setView(WTF::RefPtr<WebCore::FrameView>&&) () at /lib64/libQt5WebKit.so.5
#29 0x00007ffff5f7d87b in WebCore::FrameLoader::closeAndRemoveChild(WebCore::Frame*) () at /lib64/libQt5WebKit.so.5
```

**Comment by ValdikSS** [comment]
Ended up disabling javascript support.
