### ISSUE TITLE
Crash while using qt5c

### ISSUE THREAD

**Issue by ArsenArsen** [QuiteRSS/quiterss#984]
When running the program in my environment, which uses qt5ct in combination with i3wm and lxappearance, arc dark gtk, and the gtk style in qt5ct the program crashes with a segmentation fault with the following trace:
```
(gdb) bt
#0  0x00000000004ed0c0 in  ()
#1  0x00000000004f293c in  ()
#2  0x00007ffff2d6ef0a in qt_message_output(QtMsgType, QMessageLogContext const&, QString const&) () at /usr/lib/libQt5Core.so.5
#3  0x00007ffff2e69950 in QDebug::~QDebug() () at /usr/lib/libQt5Core.so.5
#4  0x00007fffe13bda92 in Qt5CTPlatformTheme::Qt5CTPlatformTheme() () at /usr/lib/qt/plugins/platformthemes/libqt5ct.so
#5  0x00007fffe13ba4c4 in Qt5CTPlatformThemePlugin::create(QString const&, QStringList const&) () at /usr/lib/qt/plugins/platformthemes/libqt5ct.so
#6  0x00007ffff3cc089a in QPlatformThemeFactory::create(QString const&, QString const&) () at /usr/lib/libQt5Gui.so.5
#7  0x00007ffff3cce300 in QGuiApplicationPrivate::createPlatformIntegration() () at /usr/lib/libQt5Gui.so.5
#8  0x00007ffff3cced2d in QGuiApplicationPrivate::createEventDispatcher() () at /usr/lib/libQt5Gui.so.5
#9  0x00007ffff2f64855 in QCoreApplicationPrivate::init() () at /usr/lib/libQt5Core.so.5
#10 0x00007ffff3cd041f in QGuiApplicationPrivate::init() () at /usr/lib/libQt5Gui.so.5
#11 0x00007ffff6f1c249 in QApplicationPrivate::init() () at /usr/lib/libQt5Widgets.so.5
#12 0x0000000000573c21 in  ()
#13 0x00000000004f18a1 in  ()
#14 0x0000000000443494 in main ()
```

The system used is Arch Linux x64, and I can confirm no other applications do this, including the ones I've built.

**Comment by Funcy-dcm** [comment]
Send qebug.log from quiterss

**Comment by ArsenArsen** [comment]
After recompilation it works but looks rather terrible, 
![](http://i.imgur.com/TVdn15Q.png)

I assume I was running an older commit. Excuse me for wasting your time.

**Comment by Funcy-dcm** [comment]
Menu - view - style - system

**Comment by ArsenArsen** [comment]
Oh, amazing. Thank you!
